apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    # Важно! Селектор должен совпадать с метками в Deployment выше
    app: {{ .Release.Name }}-api