apiVersion: apps/v1
kind: Deployment
metadata:
  # Имя теперь динамическое: "my-release-api"
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  # Берем количество реплик из values.yaml
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: api
          # Собираем имя образа из двух переменных: "go_blog_app:k8s"
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            # --- Вставляем переменные окружения ---
            - name: DB_HOST
              value: {{ .Values.global.env.DB_HOST | quote }}
            - name: DB_USER
              value: {{ .Values.global.env.DB_USER | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: password

            - name: DB_NAME
              value: {{ .Values.global.env.DB_NAME | quote }}
            - name: DB_PORT
              value: {{ .Values.global.env.DB_PORT | quote }}
            - name: KAFKA_BROKERS
              value: {{ .Values.global.env.KAFKA_BROKERS | quote }}
            - name: REDIS_ADDR
              value: {{ .Values.global.env.REDIS_ADDR | quote }}

          resources:
            requests:
              memory: "64Mi" # Дай мне минимум 64 Мб
              cpu: "100m" # И 10% одного ядра
            limits:
              memory: "128Mi" # Но не больше 128 Мб! (Иначе убей меня)
              cpu: "500m" # И не больше 50% ядра

          # --- ЗОНДЫ (Кубер будет тыкать палочкой в /health) ---
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5 # Подожди 5 секунд после старта
            periodSeconds: 10 # Проверяй каждые 10 сек

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
