apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "minikube-kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              # ВАЖНО: Кафка тоже получит префикс, поэтому ищем её по новому имени
              value: "{{ .Release.Name }}-kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-ui-service
spec:
  selector:
    app: {{ .Release.Name }}-kafka-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080