apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
stringData:
  # Берем пароль из values.yaml, но Кубер сам его зашифрует в Base64
  password: {{ .Values.global.env.DB_PASSWORD | quote }}