apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-blog
  template:
    metadata:
      labels:
        app: go-blog
    spec:
      containers:
        - name: go-blog-container
          image: go_blog_app:k8s # <-- Тот образ, что мы собрали внутри Minikube
          imagePullPolicy: Never  # <-- ВАЖНО: "Не качай из инета, бери локальный"
          ports:
            - containerPort: 8080
          env:
            # --- POSTGRES ---
            - name: DB_HOST
              value: "postgres-service" # Стучимся в сервис базы
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "go_blog_db"
            - name: DB_PORT
              value: "5432"

            # --- REDIS (ИСПРАВЛЕНО) ---
            - name: REDIS_ADDR
              value: "redis-service:6379" # <- Указываем имя сервиса!  <-- Формат host:port
            - name: REDIS_PASSWORD
              value: ""

            # --- KAFKA ---
            - name: KAFKA_BROKERS
              value: "kafka-service:9092"