apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'go_blog_services'
        static_configs:
          - targets:
              # Имя сервиса API (проверить kubectl get svc, обычно go-blog-app или как в app.yaml)
              - 'go-blog-app:8080'
              # Имена новых сервисов, что создали выше
              - 'publisher-metrics-service:9091'
              - 'consumer-metrics-service:9092'